/**
 * Demo seed data for PlantCareRules.
 * Values are simplified for a diploma project and should be refined
 * with agronomic sources before production use.
 */
import { PlantCategory } from '../../common/enums/plant-category.enum';
import { VarietyType } from '../../common/enums/variety-type.enum';

export const plantCareRulesSeed = [
  // ── VEGETABLES ────────────────────────────────────────────────────────────
  {
    plantSlug: 'potato',
    category: PlantCategory.Vegetable,
    supportsVarieties: true,
    varietyType: VarietyType.Ripening,
    allowedVarieties: ['early', 'normal', 'late'],
    growth: { normalDaysToHarvest: 90 },
    watering: { enabled: true, baseIntervalDays: 5, waterNeed: 'medium' },
    fertilizing: { enabled: true, firstFertilizingAfterDays: 21, baseIntervalDays: 30 },
    harvesting: { enabled: true },
    notes: 'Simplified values — refine with agronomic sources.',
  },
  {
    plantSlug: 'tomato',
    category: PlantCategory.Vegetable,
    supportsVarieties: true,
    varietyType: VarietyType.Ripening,
    allowedVarieties: ['early', 'normal', 'late'],
    growth: { normalDaysToHarvest: 90 },
    watering: { enabled: true, baseIntervalDays: 4, waterNeed: 'high' },
    fertilizing: { enabled: true, firstFertilizingAfterDays: 21, baseIntervalDays: 21 },
    harvesting: { enabled: true },
    notes: 'Simplified values.',
  },
  {
    plantSlug: 'carrot',
    category: PlantCategory.Vegetable,
    supportsVarieties: true,
    varietyType: VarietyType.Ripening,
    allowedVarieties: ['early', 'normal', 'late'],
    growth: { normalDaysToHarvest: 80 },
    watering: { enabled: true, baseIntervalDays: 5, waterNeed: 'medium' },
    fertilizing: { enabled: true, firstFertilizingAfterDays: 30, baseIntervalDays: 30 },
    harvesting: { enabled: true },
    notes: 'Simplified values.',
  },
  {
    plantSlug: 'pepper',
    category: PlantCategory.Vegetable,
    supportsVarieties: true,
    varietyType: VarietyType.Ripening,
    allowedVarieties: ['early', 'normal', 'late'],
    growth: { normalDaysToHarvest: 100 },
    watering: { enabled: true, baseIntervalDays: 4, waterNeed: 'high' },
    fertilizing: { enabled: true, firstFertilizingAfterDays: 21, baseIntervalDays: 21 },
    harvesting: { enabled: true },
    notes: 'Simplified values.',
  },
  {
    plantSlug: 'onion',
    category: PlantCategory.Vegetable,
    supportsVarieties: true,
    varietyType: VarietyType.Ripening,
    allowedVarieties: ['early', 'normal', 'late'],
    growth: { normalDaysToHarvest: 100 },
    watering: { enabled: true, baseIntervalDays: 6, waterNeed: 'medium' },
    fertilizing: { enabled: true, firstFertilizingAfterDays: 30, baseIntervalDays: 30 },
    harvesting: { enabled: true },
    notes: 'Simplified values.',
  },

  // ── TREES ─────────────────────────────────────────────────────────────────
  {
    plantSlug: 'apple',
    category: PlantCategory.Tree,
    supportsVarieties: true,
    varietyType: VarietyType.HarvestSeason,
    allowedVarieties: ['summer', 'autumn', 'winter'],
    growth: { isPerennial: true, estimatedLifespanYears: 20 },
    watering: { enabled: true, baseIntervalDays: 10, waterNeed: 'medium' },
    fertilizing: { enabled: true, firstFertilizingAfterDays: 45, baseIntervalDays: 60 },
    // Harvest disabled: no maturity/age data available at generation time
    harvesting: { enabled: false },
    notes: 'Perennial tree. Harvest not generated until maturity data is provided.',
  },
  {
    plantSlug: 'pear',
    category: PlantCategory.Tree,
    supportsVarieties: true,
    varietyType: VarietyType.HarvestSeason,
    allowedVarieties: ['summer', 'autumn', 'winter'],
    growth: { isPerennial: true, estimatedLifespanYears: 20 },
    watering: { enabled: true, baseIntervalDays: 10, waterNeed: 'medium' },
    fertilizing: { enabled: true, firstFertilizingAfterDays: 45, baseIntervalDays: 60 },
    harvesting: { enabled: false },
    notes: 'Perennial tree. Harvest not generated until maturity data is provided.',
  },
  {
    plantSlug: 'plum',
    category: PlantCategory.Tree,
    supportsVarieties: true,
    varietyType: VarietyType.Ripening,
    allowedVarieties: ['early', 'normal', 'late'],
    growth: { isPerennial: true, estimatedLifespanYears: 15 },
    watering: { enabled: true, baseIntervalDays: 10, waterNeed: 'medium' },
    fertilizing: { enabled: true, firstFertilizingAfterDays: 45, baseIntervalDays: 60 },
    harvesting: { enabled: false },
    notes: 'Perennial tree. Harvest not generated until maturity data is provided.',
  },
  {
    plantSlug: 'cherry',
    category: PlantCategory.Tree,
    supportsVarieties: true,
    varietyType: VarietyType.Ripening,
    allowedVarieties: ['early', 'normal', 'late'],
    growth: { isPerennial: true, estimatedLifespanYears: 20 },
    watering: { enabled: true, baseIntervalDays: 10, waterNeed: 'medium' },
    fertilizing: { enabled: true, firstFertilizingAfterDays: 45, baseIntervalDays: 60 },
    harvesting: { enabled: false },
    notes: 'Perennial tree. Harvest not generated until maturity data is provided.',
  },
  {
    plantSlug: 'walnut',
    category: PlantCategory.Tree,
    supportsVarieties: false,
    varietyType: VarietyType.None,
    allowedVarieties: [],
    growth: { isPerennial: true, estimatedLifespanYears: 50 },
    watering: { enabled: true, baseIntervalDays: 14, waterNeed: 'low' },
    fertilizing: { enabled: true, firstFertilizingAfterDays: 60, baseIntervalDays: 90 },
    harvesting: { enabled: false },
    notes: 'Very long-lived perennial. Harvest not generated without maturity data.',
  },

  // ── BERRIES ───────────────────────────────────────────────────────────────
  {
    plantSlug: 'strawberry',
    category: PlantCategory.Berry,
    supportsVarieties: true,
    varietyType: VarietyType.Ripening,
    allowedVarieties: ['early', 'normal', 'late'],
    growth: { normalDaysToHarvest: 60 },
    watering: { enabled: true, baseIntervalDays: 3, waterNeed: 'high' },
    fertilizing: { enabled: true, firstFertilizingAfterDays: 14, baseIntervalDays: 21 },
    harvesting: { enabled: true },
    notes: 'Simplified values.',
  },
  {
    plantSlug: 'raspberry',
    category: PlantCategory.Berry,
    supportsVarieties: true,
    varietyType: VarietyType.Ripening,
    allowedVarieties: ['early', 'normal', 'late'],
    growth: { normalDaysToHarvest: 90 },
    watering: { enabled: true, baseIntervalDays: 5, waterNeed: 'medium' },
    fertilizing: { enabled: true, firstFertilizingAfterDays: 21, baseIntervalDays: 30 },
    harvesting: { enabled: true },
    notes: 'Simplified values.',
  },
  {
    plantSlug: 'blueberry',
    category: PlantCategory.Berry,
    supportsVarieties: true,
    varietyType: VarietyType.Ripening,
    allowedVarieties: ['early', 'normal', 'late'],
    growth: { normalDaysToHarvest: 100 },
    watering: { enabled: true, baseIntervalDays: 5, waterNeed: 'high' },
    fertilizing: { enabled: true, firstFertilizingAfterDays: 21, baseIntervalDays: 30 },
    harvesting: { enabled: true },
    notes: 'Simplified values.',
  },
  {
    plantSlug: 'currant',
    category: PlantCategory.Berry,
    supportsVarieties: true,
    varietyType: VarietyType.Ripening,
    allowedVarieties: ['early', 'normal', 'late'],
    growth: { normalDaysToHarvest: 90 },
    watering: { enabled: true, baseIntervalDays: 7, waterNeed: 'medium' },
    fertilizing: { enabled: true, firstFertilizingAfterDays: 21, baseIntervalDays: 45 },
    harvesting: { enabled: true },
    notes: 'Simplified values.',
  },
  {
    plantSlug: 'gooseberry',
    category: PlantCategory.Berry,
    supportsVarieties: true,
    varietyType: VarietyType.Ripening,
    allowedVarieties: ['early', 'normal', 'late'],
    growth: { normalDaysToHarvest: 90 },
    watering: { enabled: true, baseIntervalDays: 7, waterNeed: 'medium' },
    fertilizing: { enabled: true, firstFertilizingAfterDays: 21, baseIntervalDays: 45 },
    harvesting: { enabled: true },
    notes: 'Simplified values.',
  },

  // ── FLOWERS ───────────────────────────────────────────────────────────────
  {
    plantSlug: 'rose',
    category: PlantCategory.Flower,
    supportsVarieties: false,
    varietyType: VarietyType.None,
    allowedVarieties: [],
    growth: {},
    watering: { enabled: true, baseIntervalDays: 5, waterNeed: 'medium' },
    fertilizing: { enabled: true, firstFertilizingAfterDays: 30, baseIntervalDays: 30 },
    harvesting: { enabled: false },
    notes: 'Simplified values.',
  },
  {
    plantSlug: 'marigold',
    category: PlantCategory.Flower,
    supportsVarieties: false,
    varietyType: VarietyType.None,
    allowedVarieties: [],
    growth: {},
    watering: { enabled: true, baseIntervalDays: 4, waterNeed: 'medium' },
    fertilizing: { enabled: false },
    harvesting: { enabled: false },
    notes: 'Simplified values.',
  },
  {
    plantSlug: 'lavender',
    category: PlantCategory.Flower,
    supportsVarieties: false,
    varietyType: VarietyType.None,
    allowedVarieties: [],
    growth: {},
    watering: { enabled: true, baseIntervalDays: 10, waterNeed: 'low' },
    fertilizing: { enabled: false },
    harvesting: { enabled: false },
    notes: 'Drought-tolerant. Simplified values.',
  },
  {
    plantSlug: 'sunflower',
    category: PlantCategory.Flower,
    supportsVarieties: true,
    varietyType: VarietyType.Ripening,
    allowedVarieties: ['early', 'normal', 'late'],
    growth: { normalDaysToHarvest: 90 },
    watering: { enabled: true, baseIntervalDays: 5, waterNeed: 'medium' },
    fertilizing: { enabled: true, firstFertilizingAfterDays: 30, baseIntervalDays: 40 },
    harvesting: { enabled: false },
    notes: 'Harvest disabled by default. Simplified values.',
  },
  {
    plantSlug: 'tulip',
    category: PlantCategory.Flower,
    supportsVarieties: false,
    varietyType: VarietyType.None,
    allowedVarieties: [],
    growth: {},
    watering: { enabled: true, baseIntervalDays: 7, waterNeed: 'medium' },
    fertilizing: { enabled: false },
    harvesting: { enabled: false },
    notes: 'Simplified values.',
  },

  // ── HERBS ─────────────────────────────────────────────────────────────────
  {
    plantSlug: 'basil',
    category: PlantCategory.Herb,
    supportsVarieties: false,
    varietyType: VarietyType.None,
    allowedVarieties: [],
    growth: {},
    watering: { enabled: true, baseIntervalDays: 3, waterNeed: 'high' },
    fertilizing: { enabled: true, firstFertilizingAfterDays: 21, baseIntervalDays: 30 },
    harvesting: { enabled: false },
    notes: 'Care events generated instead of harvest. Simplified values.',
  },
  {
    plantSlug: 'mint',
    category: PlantCategory.Herb,
    supportsVarieties: false,
    varietyType: VarietyType.None,
    allowedVarieties: [],
    growth: {},
    watering: { enabled: true, baseIntervalDays: 4, waterNeed: 'medium' },
    fertilizing: { enabled: false },
    harvesting: { enabled: false },
    notes: 'Simplified values.',
  },
  {
    plantSlug: 'parsley',
    category: PlantCategory.Herb,
    supportsVarieties: false,
    varietyType: VarietyType.None,
    allowedVarieties: [],
    growth: {},
    watering: { enabled: true, baseIntervalDays: 4, waterNeed: 'medium' },
    fertilizing: { enabled: false },
    harvesting: { enabled: false },
    notes: 'Simplified values.',
  },
  {
    plantSlug: 'dill',
    category: PlantCategory.Herb,
    supportsVarieties: false,
    varietyType: VarietyType.None,
    allowedVarieties: [],
    growth: {},
    watering: { enabled: true, baseIntervalDays: 4, waterNeed: 'medium' },
    fertilizing: { enabled: false },
    harvesting: { enabled: false },
    notes: 'Simplified values.',
  },
  {
    plantSlug: 'rosemary',
    category: PlantCategory.Herb,
    supportsVarieties: false,
    varietyType: VarietyType.None,
    allowedVarieties: [],
    growth: {},
    watering: { enabled: true, baseIntervalDays: 10, waterNeed: 'low' },
    fertilizing: { enabled: false },
    harvesting: { enabled: false },
    notes: 'Drought-tolerant herb. Simplified values.',
  },
];
